delete from SMA_HLX.SMA_SUMMARY@KNOXHLXPRD
where SMA_NAME='National Access Engineering SMA'
and KPI_NAME='IMS SBG Simultaneous SIP Sessions'
AND PERIOD_DATE=trunc(trunc(sysdate,'MM')-1,'MM');
INSERT INTO SMA_HLX.SMA_SUMMARY@KNOXHLXPRD
with pm_data as
(
select /*+ materialize */ SIPPA.DATETIME,
        SUM(nvl(SIPCS.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPPA.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPPC.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPIC.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPIF.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPPA.SBGSIPACTIVEOUTSESSIONS,0)) + SUM(nvl(SIPPC.SBGSIPACTIVEOUTSESSIONS,0)) + SUM(nvl(SIPIC.SBGSIPACTIVEOUTSESSIONS,0)) + SUM(nvl(SIPIF.SBGSIPACTIVEOUTSESSIONS,0)) KPI,
        count(distinct SIPPA.DATETIME) DATETIME_COUNT,
        count(distinct SIPPA.SBGV_NAME) NE_COUNT,
        'Santa Clara' LOCATION_GROUP
        from ERICSSON_SBGV.SBG_SIPPATM_SESTATS_15M SIPPA
        LEFT OUTER JOIN ERICSSON_SBGV.SBG_SIPPCTM_SESTATS_15M SIPPC
        on SIPPA.DATETIME=SIPPC.DATETIME AND SIPPA.SBGV_NAME=SIPPC.SBGV_NAME
        LEFT OUTER JOIN  ERICSSON_SBGV.SBG_SIPIFTM_SESTATS_15M SIPIF
        on SIPPA.DATETIME=SIPIF.DATETIME AND SIPPA.SBGV_NAME=SIPIF.SBGV_NAME
        LEFT OUTER JOIN ERICSSON_SBGV.SBG_SIPICTM_SESTATS_15M SIPIC
        on SIPPA.DATETIME=SIPIC.DATETIME AND SIPPA.SBGV_NAME=SIPIC.SBGV_NAME
        LEFT OUTER JOIN ERICSSON_SBGV.SBG_SIPCSTM_SESTATS_15M SIPCS
        on SIPPA.DATETIME=SIPCS.DATETIME AND SIPPA.SBGV_NAME=SIPCS.SBGV_NAME
        where (SIPPA.SBGV_NAME like 'casant%')
        and SIPPA.DATETIME >= trunc(trunc(sysdate,'MM')-1,'MM') and SIPPA.DATETIME < trunc(sysdate,'MM')
        group by SIPPA.DATETIME
        UNION
select /*+ materialize */ SIPPA.DATETIME,
        SUM(nvl(SIPCS.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPPA.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPPC.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPIC.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPIF.SBGSIPACTIVEINCSESSIONS,0)) + SUM(nvl(SIPPA.SBGSIPACTIVEOUTSESSIONS,0)) + SUM(nvl(SIPPC.SBGSIPACTIVEOUTSESSIONS,0)) + SUM(nvl(SIPIC.SBGSIPACTIVEOUTSESSIONS,0)) + SUM(nvl(SIPIF.SBGSIPACTIVEOUTSESSIONS,0)) KPI,
        count(distinct SIPPA.DATETIME) DATETIME_COUNT,
        count(distinct SIPPA.SBGV_NAME) NE_COUNT,
        'Ashburn' LOCATION_GROUP
        from ERICSSON_SBGV.SBG_SIPPATM_SESTATS_15M SIPPA
        LEFT OUTER JOIN ERICSSON_SBGV.SBG_SIPPCTM_SESTATS_15M SIPPC
        on SIPPA.DATETIME=SIPPC.DATETIME AND SIPPA.SBGV_NAME=SIPPC.SBGV_NAME
        LEFT OUTER JOIN  ERICSSON_SBGV.SBG_SIPIFTM_SESTATS_15M SIPIF
        on SIPPA.DATETIME=SIPIF.DATETIME AND SIPPA.SBGV_NAME=SIPIF.SBGV_NAME
        LEFT OUTER JOIN ERICSSON_SBGV.SBG_SIPICTM_SESTATS_15M SIPIC
        on SIPPA.DATETIME=SIPIC.DATETIME AND SIPPA.SBGV_NAME=SIPIC.SBGV_NAME
        LEFT OUTER JOIN ERICSSON_SBGV.SBG_SIPCSTM_SESTATS_15M SIPCS
        on SIPPA.DATETIME=SIPCS.DATETIME AND SIPPA.SBGV_NAME=SIPCS.SBGV_NAME
        where (SIPPA.SBGV_NAME like 'vaashb%')
        and SIPPA.DATETIME >= trunc(trunc(sysdate,'MM')-1,'MM') and SIPPA.DATETIME < trunc(sysdate,'MM')
        group by SIPPA.DATETIME
)
select
trunc(datetime,'MM') PERIOD_DATE,
'National Access Engineering SMA' SMA_NAME,
'ERI_VoLTE911' REPORT_GROUP,
'SBG' REGION_GROUP,
LOCATION_GROUP,
'IMS SBG Simultaneous SIP Sessions' KPI_NAME,
'sbgSipActiveSessions' INDICATOR_,
'MM' TIME_AGG_TYPE,
'PERC' MATH_AGG_TYPE,
97 PERCENTILE_USED,
PERCENTILE_CONT(0.97) within group (order by KPI) KPI_VALUE,
'Counter' KPI_UNITS,
300 RAW_POLLING_DURATION,
count(distinct DATETIME) PERIOD_COUNT,
avg(NE_COUNT) AVG_INSTANCE_COUNT,
sysdate REC_CREATE_DATE,
sysdate LAST_UPDATE_DATE
from pm_data
group by trunc(datetime,'MM'), LOCATION_GROUP;

